package structure;

// Generated 22 févr. 2016 20:36:59 by Hibernate Tools 3.4.0.CR1

/**
 * Personne generated by hbm2java
 */
public class Personne implements java.io.Serializable {

	private Integer id_personne;
	private String nom;
	private String prenom;
	private String login;
	private String password;

	public Personne() {
	}

	public Personne(String nom, String prenom, int idEtablissement) {
		this.nom = nom;
		this.prenom = prenom;
		// this.idEtablissement = idEtablissement;
	}

	public Personne(String nom, String prenom, String login, String password) {
		this.nom = nom;
		this.prenom = prenom;
		this.login = login;
		this.password = password;
	}

	public Personne(String nom, String prenom) {
		this.nom = nom;
		this.prenom = prenom;
	}

	public Integer getIdPersonne() {
		return this.id_personne;
	}

	public void setIdPersonne(Integer id_personne) {
		this.id_personne = id_personne;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	// public int getIdEtablissement() {
	// return this.idEtablissement;
	// }
	//
	// public void setIdEtablissement(int idEtablissement) {
	// this.idEtablissement = idEtablissement;
	// }

}
